/*
 * This Java source file was generated by the Gradle 'init' task.
 */


package com.crio.qcalc;


public class App {

    public String getGreeting() {

        return "Hello World!";

    }


   

   public static void main(String[] args) {

    System.out.println("Starting QCalc..");

    StandardCalculator calc = new StandardCalculator();

    calc.add(1, 2);
    calc.subtract(5, 2);

    calc.multiply(1, 3);

    calc.divide(6, 2);

    System.out.println(calc.getResult());
    System.out.println(calc.getGreeting());

}


}

